@token = {{login.response.body.token}}
### Login a user and store the token in a variable
# @name login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "yourpassword"
}

### Get All Books
GET http://localhost:3000/api/books
Authorization: Bearer {{token}}

### Get Book by ID
GET http://localhost:3000/api/books/4
Authorization: Bearer {{token}}

### Add a New Book

POST http://localhost:3000/api/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "year": 1925
}

### Delete Book by ID
DELETE http://localhost:3000/api/books/2
Authorization: Bearer {{token}}
